apiVersion: v1
entries:
  hello-world:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-04-19T09:59:24.148307738+03:00"
    description: A Helm chart for Kubernetes
    digest: e4186b8245faee2a622af8efe2dcc576247c3f44f94c5e54eaa2fdbcee79f03f
    name: hello-world
    type: application
    urls:
    - hello-world-0.1.0.tgz
    version: 0.1.0
generated: "2024-04-19T09:59:24.147809758+03:00"
