on:
  workflow_dispatch:
jobs:
  my-job:
    # Importing a reusable workflow from another repository and branch
    uses: ./.github/workflows/reusable-workflow.yaml
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.0'
