
name: deploy

on:
  workflow_dispatch:
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # We need this because GitHub needs to clone the branch to pipeline
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Deploy
        uses: "./.github/workflows/templates" #Just need to pass the path from action
       # Defining the variables required in our action
        with:
          version: v1.0.0
          namespace: "stage"
