name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/templates/ci-template.yaml
    with:
      config-path: "helloworld"
    secrets:
      token: "helloworld"