name: build-test-deploy
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      docker-tag:
        description: "docker-tag"
        required: true
        type: string

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      # Modified to use the node-version from the workflow inputs
      - name: install
        run: |
          echo ${{ inputs.docker-tag }}